services:
  mongodb:
    image: mongo:8.0
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mydatabase
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_ROOT_USERNAME: root
    ports:
      - '27017:27017'
    volumes:
      - ./docker/mongo/setup.js:/docker-entrypoint-initdb.d/setup.js:ro