spring:
  profiles:
    active: dev, no-security
  application:
    name: crm-analytics
  kafka:
    consumer:
      group-id: crm-analytics-consumer
      auto-offset-reset: earliest
#      key-deserializer: org.springframework.kafka.support.serializer.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  data:
    mongodb:
      host: localhost
      username: mongo
      password: mongo
      database: mydatabase

server:
  port: ${PORT:8765}

kafka-config:
  job-offer-topic: "dbserver1.public.job_offer"
  job-offer-skills-topic: "test2"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    csrf:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
