spring:
  profiles:
    active: dev, no-security, api-docs
  application:
    name: crm-analytics
  kafka:
    consumer:
      group-id: crm-analytics-consumer
      auto-offset-reset: earliest
      #      key-deserializer: org.springframework.kafka.support.serializer.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

  data:
    mongodb:
      host: ${MONGODB_HOST:localhost}
      username: ${MONGODB_USERNAME:mongo}
      password: ${MONGODB_PASSWORD:mongo}
      database: ${MONGODB_DATABASE:mydatabase}
      port: ${MONGODB_PORT:27017}

server:
  port: ${PORT:8765}

kafka-config:
  job-offer-topic: "dbserver1.public.job_offer"
  contact-topic: "dbserver1.public.contact"
  customer-topic: "dbserver1.public.customer"
  message-topic: "dbserver1.public.message"
  professional-topic: "dbserver1.public.professional"

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    csrf:
      enabled: false

openapi:
  base-url: ${OPENAPI_BASE_URL:http://localhost:${server.port}}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
